import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header'
import { Hero } from '@/components/Hero'
import { Projects } from '@/components/Projects'
import { Footer } from '@/components/Footer'
import { About } from '@/components/About'

export default function Home() {
  return (
    <>
    
      <div className='container'>
        <Head>
          <title>Thiago Moura | Página Inicial</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.svg" />
        </Head>
        <Header />
        <Hero />
        <Projects />
        <About />
      </div>
      <Footer />
    </>
  )
}
